local ItemData = {
	["StandArrow"] = {
		Image = "rbxassetid://123421828753827",
		Description = "Gives you a random stand.",
	},

	["Rokakaka"] = {
		Image = "rbxassetid://76580142242026",
		Description = "Resets your stand, race, specialty, and talents.",
	},

	["PurpleRokakaka"] = {
		Image = "rbxassetid://71009671115143",
		Description = "Resets your stand and talents, but not your race or specialty.",
	},

	["BlueRokakaka"] = {
		Image = "rbxassetid://119037530867572",
		Description = "Resets your specialty race, and talents, but not your stand.",
	},

	["StoneMask"] = {
		Image = "rbxassetid://104187809779470",
		Description = "Changes your race from human to vampire.",
	},
}

return ItemData
