local StoneFree = require(script.Parent:WaitForChild("StoneFree"))
local CombatUtils = require(game.ServerScriptService.BasicCombat:WaitForChild("CombatUtils"))

local CooldownUpdateEvent = game.ReplicatedStorage
	:WaitForChild("Shared")
	:WaitForChild("BasicCombat")
	:WaitForChild("UI")
	:WaitForChild("CooldownUpdateEvent")

local AbilityRegistry = {}

local lastTimeEraseUse = {}

--------------------------------------------------------------------
-- Ability Types (Sent to Client)
-- Types: "Press", "Hold", "Toggle"
--------------------------------------------------------------------
AbilityRegistry.AbilityTypes = {
	[1] = "Press",
	[2] = "Press",
	[3] = "Press",
	[4] = "Press",
}

--------------------------------------------------------------------
-- Ability 1 - Chop (Press)
--------------------------------------------------------------------
AbilityRegistry[1] = {
	Name = "Chop",
	Type = "Press",
	Cooldown = 10,
	Execute = function(standModel, player)
		StoneFree.StringForm(standModel)
	end,
}

--------------------------------------------------------------------
-- Ability 2 - Splatter (Press)
--------------------------------------------------------------------
AbilityRegistry[2] = {
	Name = "Splatter",
	Type = "Press",
	Cooldown = 12,
	Execute = function(standModel, player)
		StoneFree.Grapple(standModel)
	end,
}

--------------------------------------------------------------------
-- Ability 3 - Teleport (Press)
--------------------------------------------------------------------
AbilityRegistry[3] = {
	Name = "Teleport",
	Type = "Press",
	EndlagCancel = true,
	Cooldown = 12,
	Execute = function(standModel, player)
		StoneFree.StringTrap(standModel)
	end,
}

--------------------------------------------------------------------
-- Ability 4 - TimeErase (Press)
--------------------------------------------------------------------
AbilityRegistry[4] = {
	Name = "TimeErase",
	Type = "Press",
	Hyperarmor = true,
	Cooldown = 30,
	EndlagCancel = true,

	BypassGlobalCooldown = true,

	Execute = function(standModel, player)
		StoneFree.Barrage(standModel)
	end,
}

return AbilityRegistry
